# 利用Python学习线性代数 -- 1.3 向量方程
## 向量代数
利用Numpy，可以很简单的实现向量加减、向量与标量的乘法。
例如

In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [2]:
# 例1
u = np.array([[1, -2]]).T
v = np.array([[2, -5]]).T
print(u)
print(v)
print(4*u)
print(-3*v)
print(4*u - 3*v)

[[ 1]
 [-2]]
[[ 2]
 [-5]]
[[ 4]
 [-8]]
[[-6]
 [15]]
[[-2]
 [ 7]]


但是，为了加深理解，这里不借用Numpy，而是用原生的Python类型实现一个向量类，实现基本向量代数。

In [3]:
class Vector:
    """用Python实现一个向量类，不使用Numpy."""
    def __init__(self, data:list):
        """data应该是一个列表"""
        if not isinstance(data, list):
            raise ValueError()
        self._data = data
    
    def __repr__(self):
        return "[" + "\n".join(str(x) for x in self._data) + "]"

Vector类还没有实现向量代数，只支持根据一个列表构造一个Vector类，支持打印成一列数字。
例如

In [4]:
u = Vector([1, -2])
v = Vector([2, -5])
print(u)
print(v)
# 以下运算不支持
print(4*u)
print(-3*v)
print(4*u - 3*v)

[1
-2]
[2
-5]


TypeError: unsupported operand type(s) for *: 'int' and 'Vector'

然后增加如下代数计算功能：
    1. 向量加法: **u** + **v** 是 **u** 和 **v** 对应元素想家所得的向量
    2. 标量乘法: c **u** 是 **u** 的每个元素乘以c
    3. 向量减法: **u** - **v** = **u** + (-**v**)

另外，还可以扩展标量与向量的加法，向量与向量的乘法，矩阵乘法(Python中的@操作符)这三个操作。
* 标量与向量的加法：将标量加到向量的每一个元素上，形成新的向量
* 向量与向量的乘法：向量对应元素相乘，形成新的向量
* 矩阵乘法：两个向量的点积，即对应元素相乘，将所有乘积加起来

在Python中，重载+ - * / 等运算符，可以通过实现特殊方法来实现。
例如，一个类的实例x与其它类的实例y相加，x+y，会调用x类的 __add__ 方法。
更多细节可以参考Python的[数据模型文档](https://docs.python.org/3/reference/datamodel.html)。

In [5]:
class Vector:
    """用Python实现一个向量类，不使用Numpy."""
    def __init__(self, data:(list, tuple)):
        """data应该是一个列表或元组"""
        self._data = tuple(data)
    
    def __getitem__(self, index):
        """使下标语法和迭代生效：即x[i]有效."""
        return self._data[index]
    
    def __radd__(self, other):
        """标量或向量other与向量self相加，等价于self+other."""
        return self + other
    
    def __add__(self, other):
        """
        加法，返回元素相加后的Vector.
        
        若other是Vector，list或tuple，返回元素相加的结果；
        若other 是标量，则扩展为值全为other的向量。
        与书不一致，与Numpy一致。
        """ 
        if isinstance(other, (float, int)):
            return Vector([other + i for i in self])
        if isinstance(other, (Vector, list, tuple)):
            return Vector(left + right for left, right 
                         in zip(self, other))
        raise ValueError("the parameter is in wrong type")
    
    def __sub__(self, other):
        """
        减法，返回元素相加后的Vector.
        
        若other是Vector，list或tuple，返回元素相减的结果；
        若other 是标量，则扩展为值全为other的向量。
        与书不一致，与Numpy一致。
        """ 
        if isinstance(other, (float, int)):
            return Vector(i - other for i in self)
        if isinstance(other, (Vector, list, tuple)):
            return Vector(i - j for i, j 
                          in zip(self, other))
        raise ValueError("the parameter is in wrong type")
        
    def __rsub__(self, other):
        """标量或列表other与向量self相减，等价于self-other."""
        return other - self
    
    def __mul__(self, other):
        """
        乘法，返回元素相乘后的Vector.
        
        若other 是标量，则为标量乘向量。
        若other是Vector，list或tuple，返回元素相乘的结果；
        与书不一致，与Numpy一致。
        """ 
        if isinstance(other, (float, int)):
            return Vector(other * i for i in self)
        if isinstance(other, (Vector, list, tuple)):
            return Vector(i * j for i, j in zip(self, other))
        raise ValueError("the parameter is in wrong type")
        
    def __rmul__(self, other):
        return self * other 
    
    def __matmul__(self, other):
        if isinstance(other, (Vector, list, tuple)):
            return sum(i * j for i, j in zip(self, other))
        raise ValueError("the parameter is in wrong type")
    
    def __rmatmul__(self, other):
        return self @ other

    def __repr__(self):
        return "[" + "\n ".join(str(x) for x in self._data) + "]"

In [6]:
u = Vector([1, -2])
v = Vector([2, -5])
print(u)
print(v)
print(4*u)
print(-3*v)
print(4*u - 3*v)

[1
 -2]
[2
 -5]
[4
 -8]
[-6
 15]
[-2
 7]


In [7]:
u @ v

12

In [8]:
v @ u

12